version: '3.8'

services:
  plant:
    build: ./plant
    image: garden/plant
    container_name: plant_service
    environment:
      - PORT=3000
      - ELASTIC_URL=http://es01:9200
    ports:
      - 3000:3000
    volumes:
      - ./plant/src/:/app/src/ # FOR HOT RELOAD ONLY
    depends_on:
      - es01
      - es02
    networks:
      - esnet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    volumes:
#      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    volumes:
#      - data02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

  elasticsearchhq:
    image: elastichq/elasticsearch-hq:latest
    container_name: elasticsearchhq
    environment:
      - HQ_DEFAULT_URL=http://es01:9200
    ports:
      - 5000:5000
    networks:
      - esnet

networks:
  esnet:
    driver: bridge

